<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.22000.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ApplicationIcon />
    <AssemblyName>CukTechController</AssemblyName>
    <RootNamespace>CukTechController</RootNamespace>
    <Version>0.1.0</Version>
    <!-- 注意: NativeAOT 与 WPF 不兼容; 发布使用 dotnet publish 加 self-contained 参数 -->
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2210.55" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="OxyPlot.Wpf" Version="2.2.0" />
  </ItemGroup>
</Project>
